name: irccloud-desktop
version: '0.6.0'
summary: IRCCloud Desktop App
description: |
  IRCCloud Desktop App
icon: assets/irccloud-desktop.png

grade: stable
confinement: strict

parts:
  irccloud-desktop:
    plugin: dump
    source: https://github.com/irccloud/irccloud-desktop/releases/download/v$SNAPCRAFT_PROJECT_VERSION/irccloud-desktop_$SNAPCRAFT_PROJECT_VERSION_amd64.deb
    source-type: deb
    prepare: |
      sed -i 's@Icon=irccloud-desktop@Icon=${SNAP}/usr/share/icons/hicolor/256x256/apps/irccloud-desktop.real.png@' usr/share/applications/irccloud-desktop.desktop
      execstack --clear-execstack opt/IRCCloud/irccloud-desktop
    build-packages:
    - execstack
    after:
    - alsa
    - desktop-gtk2
    - icon
    stage-packages:
    - gconf2
    - libgl1-mesa-glx
    - libglu1-mesa
    - libnotify4
    - libnspr4
    - libnss3
    - libpulse0
    - libxss1
    - libxtst6
  
  alsa:
    after: [alsa-lib, alsa-plugins]
  alsa-plugins:
    after: [alsa-lib]

  icon:
    source: assets
    plugin: dump
    organize:
      irccloud-desktop.png: usr/share/icons/hicolor/256x256/apps/irccloud-desktop.real.png
    stage:
    - usr/share/icons/hicolor/256x256/apps/irccloud-desktop.real.png

apps:
  irccloud-desktop:
    command: desktop-launch alsa-launch $SNAP/opt/IRCCloud/irccloud-desktop
    # Correct the TMPDIR path for Chromium Framework/Electron to
    # ensure libappindicator has readable resources.
    environment:
      TMPDIR: $XDG_RUNTIME_DIR
    desktop: usr/share/applications/irccloud-desktop.desktop
    plugs:
    - browser-support
    - gsettings
    - home
    - mount-observe
    - network
    - network-bind
    - opengl
    - pulseaudio
    - unity7
    - x11
